services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
        volumes:
            - ~/docker_vol/mongo:/data/db
    meili:
        container_name: meilisearch
        image: getmeili/meilisearch
        ports:
            - "7700:7700"
        environment:
            MEILI_MASTER_KEY: ${MEILI_PASS}
        volumes:
            - ~/docker_vol/meilisearch:/data.ms
    rabbit:
        container_name: rabbit
        image: rabbitmq:3-management
        hostname: "rabbit"
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
            RABBITMQ_DEFAULT_VHOST: "/"
        volumes:
            - ~/docker_vol/rabbit:/var/lib/rabbitmq
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ~/docker_vol/redis:/data
    influx:
        container_name: influx
        image: influxdb
        ports:
            - "8086:8086"
        environment:
            DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USER}
            DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASS}
            DOCKER_INFLUXDB_INIT_ORG: la-catalog
            DOCKER_INFLUXDB_INIT_BUCKET: la-catalog
        volumes:
            - ~/docker_vol/influx:/var/lib/influxdb2
