name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: curl -s https://install.zerotier.com | sudo bash
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10"
          enable-pep582: true
      - run: pdm install
      # - run: pdm publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
      # old, use as reference
      # - uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      #   with:
      #     user: ${{ secrets.PYPI_USER }}
      #     password: ${{ secrets.PYPI_PASSWORD }}
      #     repository_url: http://${{ secrets.PYPI_ADDRESS }}:${{ secrets.PYPI_PORT }}/simple/
