name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pdm
        uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10"
          enable-pep582: true

      - name: Update and test packages
        run: |
          pdm install
          pdm update --unconstrained --save-exact
          pdm run unittest
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update packages
          committer_name: actions
          committer_email: actions@github.com
