name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main
        with:
          python-version: "3.10"
          enable-pep582: true
      - run: pdm install
      - run: pdm update
      - run: pdm run unittest
      - uses: EndBug/add-and-commit@v9
        with:
          message: Workflow fix
          committer_name: actions
          committer_email: actions@github.com
