name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

env:
  PYTHON_VERSION: "3.10"

jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pdm
        uses: pdm-project/setup-pdm@v2.7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-pep582: true

      - name: Update and test packages
        run: |
          pdm install
          pdm update --unconstrained --save-exact
          pdm run unittest

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.ref_name }}
          head: HEAD
          extra_args: --debug --only-verified --fail
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Update packages
          default_author: github_actions
