name: Test code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: "3.10"

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pdm
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          enable-pep582: true

      - name: Format and test code
        run: |
          pdm install
          pdm run black
          pdm run isort
          pdm run unittest

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Format code
          default_author: github_actions
